### ISSUE TITLE
[bug?] property server is not registered

### ISSUE THREAD

**Issue by null-qwerty** [Mcayear/koishi-plugin-webhook-trigger-action#2]
在加载配置后日志出现如下报错
```
Error: property server is not registered, declare it as `inject` to suppress this warning
                            at checkInject (/koishi/node_modules/cordis/lib/index.cjs:852:36)
                            at Object.get (/koishi/node_modules/cordis/lib/index.cjs:863:9)
                            at Object.apply (/koishi/node_modules/koishi-plugin-webhook-trigger-action/lib/index.js:64:17)
                            at _MainScope.apply (/koishi/node_modules/cordis/lib/index.cjs:516:26)
                            at /koishi/node_modules/cordis/lib/index.cjs:540:36
                            at _MainScope.ensure (/koishi/node_modules/cordis/lib/index.cjs:293:18)
                            at _MainScope.start (/koishi/node_modules/cordis/lib/index.cjs:540:12)
                            at _MainScope.init (/koishi/node_modules/cordis/lib/index.cjs:340:12)
                            at new MainScope (/koishi/node_modules/cordis/lib/index.cjs:468:12)
                            at Proxy.plugin (/koishi/node_modules/cordis/lib/index.cjs:655:15)
```

**Comment by Apricityx** [comment]
对接此项目时出现相同报错
https://github.com/YDHusky/LiteLoaderQQNT-OneBotApi/blob/main/README.md

**Comment by Mcayear** [comment]
稍后我看看

**Comment by Mcayear** [comment]
尝试最新版本
